config/routes.rb
Rails.application.routes.draw do
  resources :employments

  root 'welcome#index'

  post 'welcome', to: 'welcome#set_current_year'

  get 'tenants/roles', to: 'welcome#roles'
  post 'tenants/roles', to: 'welcome#set_role'

  resources :customers do
    resources :records
  end

  resources :books do
    resources :fees do
      resources :fee_records

      get 'monthly_report', to: 'fees#show_monthly_report'

      get 'daily_trend', to: 'fees#show_daily_trend'
    end

    get 'monthly_report', to: 'books#show_monthly_report'
  end

  devise_for :tenants

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_action :authenticate_tenant!
  before_action :set_current_companies

  def index
    @current_companies = Company.joins(:employments)
                                .where("tenant_id = ?", current_tenant.id)
    @books = Book.all.where(company_id:  session[:current_companies])
  end

  def set_current_year
    session[:return_to] = request.referer
    session[:current_year] = welcome_params['year']
    redirect_to session[:return_to]
  end

  #---2021-01-27----
  def roles
    @tenants = Tenant.all
  end

  def set_role
    #
    @tenant = Tenant.find_by_id(params[:tenant_id])
    #binding.pry
    #
    respond_to do |format|
      if @tenant.update_attribute(:role, params[:tenant][:role])
        format.html { redirect_to tenants_roles_path, notice: '费项更新成功.' }
      end
    end

  end

  private

  def set_current_companies
    #@current_companies =
    session[:current_companies] = Company.joins(:employments)
                                         .where("tenant_id = ?", current_tenant.id)
                                         .collect(&:id)
    #binding.pry
  end

  def welcome_params
    params.require(:welcome).permit(:year, :role, :tenant_id)
  end

end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/index.html.erb
<div class="row">
  <% if tenant_signed_in? %>

    <div class="col-xs-6">
      <%= form_for :welcome, :url => { :controller => :welcome, :action => 'set_current_year' },
                   :html => { :id => 'year_form', :method => "post" } do |f| %>
        <label style="font-size:18px">年份：</label>
        <%= f.select :year,
                     options_for_select(['2020', '2021', '2022', '2023', '2024', '2025', '2026', '2027', '2028', '2029', '2030', '2031', '2032', '2033', '2034', '2035', '2036', '2037', '2038', '2039', '2040'], session[:current_year]),
                     {},
                     { style: 'font-size:18px', onchange: "this.form.submit()" }
        %>
      <% end %>
      <div>Welcome: <%= current_tenant.name   %> ( <%= current_tenant.role %>)</div>
    </div>
    <br/>
    <div class="col-xs-3" style="text-align: right">
    <%#= link_to('编辑个人信息', edit_tenant_registration_path, :class => 'btn btn-primary') %>
    </div>
    <div class="col-xs-6" style="text-align: right">
      <% if current_tenant.role == 'admin' then %>
        <%= link_to '新收支账本', new_book_path, class: 'btn btn-primary' %>
      <% end %>
      <%= link_to('登出', destroy_tenant_session_path, :method => :delete, :class => 'btn btn-primary') %>
    </div>
  <% end %>
</div>



<div class="masthead" style="font-size: 30px">
  <h2 class="text-muted">财务系统</h2>
  <nav>
    <ul class="nav nav-justified">
      <li>
        <%= link_to '客户应收应付', customers_path %>
      </li>
      <% @books.each do |b| %>
        <li>
          <%= link_to b.book_name, book_path(b) %>
        </li>
      <% end %>
      <% if current_tenant.role == 'admin' then %>
        <li> <%= link_to '管理权限', tenants_roles_path %></li>
<!--        <li> <%#= link_to "注册用户", new_tenant_registration_path %> </li>-->
      <% end %>

    </ul>
  </nav>
</div>

app/views/welcome/roles.html.erb
<div class="fixed-box">
  <ol class="breadcrumb">
    <li><%= link_to '主页', root_path %></li>
  </ol>
</div>
<div >
  <%= link_to('登出', destroy_tenant_session_path, :method => :delete, :class => 'btn btn-primary') %>
</div>

<br>
<div class=divTable">
  <% @tenants.each do |r| %>
    <div class="divTableRow">
      <div class="divTableCell">
        <%= r.id %>
      </div>
      <div class="divTableCell">
        <%= r.name %>
      </div>
      <div class="divTableCell">
        <%= r.mobile %>
      </div>
      <div class="divTableCell">
        <%= form_for r, :url => { :controller => :welcome, :action => 'set_role',
                                  :tenant_id => r.id.to_s },
                     :html => { :id => "role_select_"+r.id.to_s, :method => "post" } do |f| %>

          <%= f.select :role,
                       options_for_select(['','admin', 'edit', 'view'], r.role),
                       {},
                       { style: 'font-size:18px', onchange: "this.form.submit()" }
          %>

        <% end %>
      </div>
      <div>
        <%#= check_box_tag "cleaner[city_ids][]", city.id, @cleaner.cities.include?(city) %>
      </div>
      <div class="divTableCell">
        <%= link_to '编辑', employments_path(:tenant_id => r.id) %>
      </div>

    </div>
  <% end %>

  </div>
  <br>