config/routes.rb
Rails.application.routes.draw do
  resources :employments

  root 'welcome#index'

  post 'welcome', to: 'welcome#set_current_year'

  get 'tenants/roles', to: 'welcome#roles'
  post 'tenants/roles', to: 'welcome#set_role'

  resources :customers do
    resources :records
  end

  resources :books do
    resources :fees do
      resources :fee_records

      get 'monthly_report', to: 'fees#show_monthly_report'

      get 'daily_trend', to: 'fees#show_daily_trend'
    end

    get 'monthly_report', to: 'books#show_monthly_report'
  end

  devise_for :tenants

end

app/models/customer.rb
class Customer < ActiveRecord::Base
  validates :cname, presence: true, uniqueness: {scope: :company}

  has_many :records, dependent: :destroy
  belongs_to :company

end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: [:new, :show, :edit, :update, :destroy]

  def index
    @companies = Company.joins(:employments)
                        .where("tenant_id = ?", current_tenant.id)

    @company_ids = @companies.collect(&:id)
    @customer_ids = Customer.where("company_id in (?) ", @company_ids).collect(&:id)

    @customer_total = Record.select('com.name, sum(credit) credit, sum(debit) debit, sum(bad) bad')
                            .joins('INNER JOIN customers c on records.customer_id = c.id')
                            .joins('INNER JOIN companies com on c.company_id = com.id ')
                            .where('customer_id in (?)  and left(records.updated_at,4) = ?',
                                   @customer_ids, session[:current_year])
                            .group('com.name')


    @customer_group = Customer.select('com.name, customers.id, customers.cname, sum(records.credit) as credit,
                                sum(records.debit) as debit, sum(records.bad) as bad')
                              .joins('LEFT OUTER JOIN records on customers.id = records.customer_id
                                  and left(records.updated_at,4) = ', session[:current_year])
                              .joins('INNER JOIN companies com on customers.company_id = com.id ')
                              .where('customers.company_id in (?) ', @company_ids)
                              .group('com.name, customers.id, customers.cname')
                              .order('customers.id asc')
    #binding.pry

  end

  def new
    @customer = Customer.new
  end

  def create

    #render plain: params[:customer].inspect
    @customer = Customer.new(customer_params)

    respond_to do |format|
      if @customer.save
        format.html { redirect_to @customer, notice: '客户创建成功.' }
        #format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :new }
        #format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end

  end

  def edit
    if Customer.find_by_id(params[:id])
      @customer = Customer.find(params[:id])
    else
      redirect_to customers_path
    end
  end

  def update
    if Customer.find_by_id(params[:id])
      @customer = Customer.find(params[:id])

      if @customer.update(customer_params)
        redirect_to @customer
      else
        render 'edit'
      end
    else
      redirect_to customers_path
    end
  end

  def show

    if Customer.find_by_id(params[:id])
      @customer = Customer.find(params[:id])
      @records = @customer.records.where('left(updated_at,4) =?', session[:current_year]).order("id DESC")
      @debit_sum = @records.sum("debit").round(2)
      @credit_sum = @records.sum("credit").round(2)
      @bad_sum = @records.sum("bad").round(2)
      @remain_sum = (@credit_sum - @debit_sum + @bad_sum).round(2)
    else
      redirect_to customers_path
    end
  end

  def destroy
    if Customer.find_by_id(params[:id])
      @customer = Customer.find(params[:id])
      @customer.destroy
    end

    redirect_to customers_path
  end

  private



  # Use callbacks to share common setup or constraints between actions.
  def set_customer
    #binding.pry
    @companies = Company.joins(:employments).where("tenant_id = ?", current_tenant.id)
    @customer = Customer.find_by_id(params[:id])

  end

  def customer_params
    params.require(:customer).permit(:cname, :phone_no, :company_id)
  end

end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_cust_form.html.erb
<%= form_for(@customer) do |f| %>

  <% if @customer != nil and @customer.errors.any? %>
    <div id="error_explanation">
      <h3>有错误导致不能保存数据：</h3>
      <ul>
        <% @customer.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <br>

  <div class="row">
    <%= f.label '公司名称', class: 'col-xs-4 control-label' %>
    <%# select_tag "people", options_from_collection_for_select(@companies, "id", "name") %>

    <%= f.select :company_id,
                 options_for_select( @companies.all.collect {|p| [ p.name, p.id ] } ),
                 {:include_blank => true},
                 { style: 'font-size:18px' }
    %>
  </div>
  <div class="row">
    <%= f.label '客户名称', class: 'col-xs-4 control-label' %>
    <div class="col-xs-4">
      <%= f.text_field :cname, class: 'form-control' %>
    </div>
  </div>

  <div class="row">
    <%= f.label '电话号码', class: 'col-xs-4 control-label' %>
    <div class="col-xs-4">
      <%= f.text_field :phone_no, class: 'form-control' %>
    </div>
  </div>

  <div class="actions">
    <div class="col-xs-6">
      <%= f.submit '保存', class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

app/views/customers/edit.html.erb
<% content_for :title, '编辑客户' %>
<%= link_to '返回', customer_path(@customer),  class: 'btn btn-primary'  %>
<br>

<%= render 'cust_form' %>

app/views/customers/index.html.erb
<% content_for :title, '客户列表' %>

<div class="fixed-box">
  <ol class="breadcrumb">
    <li><%= link_to '主页', root_path %></li>
    <li class="active">客户列表</li>
  </ol>
</div>

<br>

<div class="row">
  <div class="col-xs-3 col-md-1">
    <% if current_tenant.role == 'edit' or current_tenant.role == 'admin' then %>
      <%= link_to '新建客户',
                  new_customer_path(
                    :com_id => @companies.collect(&:id).join(','),
                    :com_name => @companies.collect(&:name).join(',')
                  ),
                  class: 'btn btn-primary' %>
    <% end %>
  </div>
  <div class="" style="text-align: right">
    <%= link_to('登出', destroy_tenant_session_path, :method => :delete, :class => 'btn btn-primary') %>
  </div>
</div>
<br>

<div class="table sumTable">
  <div class="theader ">
    <div class="table_header">公司</div>
    <div class="table_header">总应收</div>
    <div class="table_header">总已收</div>
    <div class="table_header">总坏账</div>
    <div class="table_header">总未收</div>
  </div>


  <% @customer_total.each do |rec|
    #assing values to credit debit and bad test if they are nil

    cr = rec.credit.nil? ? 0 : rec.credit
    de = rec.debit.nil? ? 0 : rec.debit
    bad = rec.bad.nil? ? 0 : rec.bad
  %>
    <div class="table_row">
      <div class='table_small'>
        <div class='table_cell'>公司</div>
        <div class="table_cell" data-title="公司"><%= rec.name %></div>
      </div>
      <div class='table_small'>
        <div class='table_cell'>应收</div>
        <div class="table_cell" data-title="应收"><%= de.round(2) %></div>
      </div>
      <div class='table_small'>
        <div class='table_cell'>已收</div>
        <div class="table_cell" data-title="已收"><%= cr.round(2) %></div>
      </div>
      <div class='table_small'>
        <div class='table_cell'>坏账</div>
        <div class="table_cell" data-title="坏账"><%= bad.round(2) %></div>
      </div>
      <div class='table_small'>
        <div class='table_cell'>未收</div>
        <div class="table_cell" data-title="未收" <% if cr - de + bad < 0%> style="color:red" <% end %> ><%= (cr - de + bad).round(2) %></div>
      </div>
    </div>
  <% end %>


</div>

<div class="table listTable">
  <div class="theader">
    <div class="table_header">公司</div>
    <div class="table_header">客户</div>
    <div class="table_header">应收</div>
    <div class="table_header">已收</div>
    <div class="table_header">坏账</div>
    <div class="table_header">未收</div>
  </div>


  <%
    @customer_group.each do |rec|
      cr = rec.credit.nil? ? 0 : rec.credit
      de = rec.debit.nil? ? 0 : rec.debit
      bad = rec.bad.nil? ? 0 : rec.bad
      remain = cr - de + bad
  %>
    <div class="table_row">
      <div class='table_small'>
        <div class='table_cell'>公司</div>
        <div class="table_cell" data-title="公司"><%= rec.name %></div>
      </div>
      <div class='table_small'>
        <div class='table_cell'>客户</div>
        <div class="table_cell" data-title="客户"><%= link_to rec.id.to_s+"."+rec.cname, customer_path(rec.id) %></div>
      </div>
      <div class='table_small'>
        <div class='table_cell'>应收</div>
        <div class="table_cell numeric" data-title="应收"><%= de.to_f.round(2) %></div>
      </div>
      <div class='table_small'>
        <div class='table_cell'>已收</div>
        <div class="table_cell numeric" data-title="已收"><%= cr.to_f.round(2) %></div>
      </div>
      <div class='table_small'>
        <div class='table_cell'>坏账</div>
        <div class="table_cell numeric" data-title="坏账"><%= bad.to_f.round(2) %></div>
      </div>
      <div class='table_small'>
        <div class='table_cell'>未收</div>
        <div class="table_cell numeric" data-title="未收" <% if remain < 0 %> style="color:red" <% end %> ><%= remain.to_f.round(2) %></div>
      </div>
    </div>
  <% end %>

</div>

app/views/customers/new.html.erb
<% content_for :title, '新建客户' %>

<%= link_to '返回客户列表', customers_path, class:'btn btn-primary' %>
<br>
<br>

<%= render 'cust_form' %>

app/views/customers/show.html.erb
<div class="fixed-box">
  <ol class="breadcrumb">
    <li><%= link_to '主页', root_path %></li>
    <li><%= link_to '客户列表', customers_path %></li>
    <li class="active"><%= @customer.cname %></li>
  </ol>
</div>

<% content_for :title, @customer.cname + '收支信息' %>

<!--如果不是管理员不显示编辑栏-->
<% if current_tenant.role == 'edit' or current_tenant.role == 'admin' then %>
  <div class="divTable">
    <%= form_for([@customer, @customer.records.build]) do |f| %>
      <div id="sandbox-container" class="numeric" data-title="日期">
        <label for="date_input">日期:</label>
        <%= f.text_field :updated_at, 'data-provide' => 'datepicker',
                         value: (Time.now.strftime('%Y') > session[:current_year]) ? session[:current_year] + '/12/31' : Time.now.strftime('%Y/%m/%d'),
                         style: ' width:90%;',
                         id: 'date_input'
        %>
        <script>
            $(document).ready(function () {
                $('#sandbox-container input').datepicker({
                    format: "yyyy/mm/dd",
                    language: "zh-CN",
                    todayHighlight: true
                });
            });
        </script>
      </div>
      <div id="debitdiv" class="numeric" data-title="应收">
        <label for="debit_input">应收:</label>

        <%= f.number_field :debit, value: 0, min: 0, max: 999999, inputmode: "numeric", :step => '0.01',
                           pattern: "[0-9]*",
                           id: 'debit_input',
                           style: ' width:90%;',
                           class: 'amount_input',
                           onfocus: "if(this.value == '0') { this.value = ''; }",
                           onblur: "if(this.value == '') { this.value = 0 ; }" %>
      </div>
      <div class="numeric" data-title="已收">
        <label for="credit_input">已收:</label>
        <%= f.number_field :credit, value: 0, min: 0, max: 999999, inputmode: "numeric",
                           :step => '0.01',
                           pattern: "[0-9]*",
                           id: 'credit_input',
                           style: ' width:90%;',
                           class: 'amount_input',
                           onfocus: "if(this.value == '0') { this.value = ''; }",
                           onblur: "if(this.value == '') { this.value = 0 ; }" %>
      </div>
      <div class="numeric" data-title="坏账">
        <label for="bad_input">坏收:</label>
        <%= f.number_field :bad, value: 0, min: 0, max: 999999, inputmode: "numeric",
                           :step => '0.01',
                           pattern: "[0-9]*",
                           id: 'bad_input',
                           style: ' width:90%;',
                           class: 'amount_input',
                           onfocus: "if(this.value == '0') { this.value = ''; }",
                           onblur: "if(this.value == '') { this.value = 0 ; }" %>
      </div>
      <div class="numeric" data-title="备注">
        <label for="comment_input">备注:</label>
        <%= f.text_field :comment, id: 'comment_input', style: ' width:90%;' %>
      </div>
      <div class=""> <%= f.submit '保存新记录', class: 'btn btn-primary btn-sm btn-block btn-submit' %></div>
    <% end %>
  </div>
<% end %>

<br>

<div class="table sumTable">
  <div class="theader">
    <div class="table_header">客户名称</div>
    <div class="table_header">总应收</div>
    <div class="table_header">总已收</div>
    <div class="table_header">总坏账</div>
    <div class="table_header">总未收</div>
  </div>
  <div class="table_row">
    <div class='table_small'>
      <div class='table_cell'>客户名称</div>
      <div class="table_cell head_sum" data-title="客户名称"><%= @customer.id.to_s+"."+@customer.cname %></div>
    </div>
    <div class='table_small'>
      <div class='table_cell sumTable'>总应收</div>
      <div class="table_cell head_sum" data-title="应收"><%= @debit_sum %></div>
    </div>
    <div class='table_small'>
      <div class='table_cell'>总已收</div>
      <div class="table_cell head_sum" data-title="已收"><%= @credit_sum %></div>
    </div>
    <div class='table_small'>
      <div class='table_cell'>总坏账</div>
      <div class="table_cell head_sum" data-title="坏账"><%= @bad_sum %></div>
    </div>
    <div class='table_small'>
      <div class='table_cell'>总未收</div>
      <% if @remain_sum < 0 %>
        <div class="table_cell head_sum" style="color:red" data-title="未收"><%= @remain_sum %></div>
      <% else %>
        <div class="table_cell head_sum" data-title="未收"><%= @remain_sum %></div>
      <% end %>
    </div>
  </div>
</div>



<div class="table listTable">
  <div class="theader">
    <div class="table_header">日期</div>
    <div class="table_header">应收</div>
    <div class="table_header">已收</div>
    <div class="table_header">坏账</div>
    <div class="table_header">未收</div>
    <div class="table_header">备注</div>
    <% if current_tenant.role == 'edit' or current_tenant.role == 'admin' then %>
      <div class="table_header"></div>
      <div class="table_header"></div>
    <% end %>
  </div>


  <% @records.each do |record|
    remain = (record.credit.to_f - record.debit.to_f + record.bad.to_f).round(2)
  %>
    <div class="table_row">
      <div class='table_small'>
        <div class='table_cell'>日期</div>
        <div class="table_cell" data-title="日期"><%= record.updated_at.strftime("%Y/%m/%d") %></div>
      </div>
      <div class='table_small'>
        <div class='table_cell'>应收</div>
        <div class="table_cell numeric" data-title="应收"><%= record.debit %></div>
      </div>
      <div class='table_small'>
        <div class='table_cell'>已收</div>
        <div class="table_cell numeric" data-title="已收"><%= record.credit %></div>
      </div>
      <div class='table_small'>
        <div class='table_cell'>坏账</div>
        <div class="table_cell numeric" data-title="坏账"><%= record.bad %></div>
      </div>
      <div class='table_small'>
        <div class='table_cell'>未收</div>
        <% if remain < 0 %>
          <div class="table_cell numeric" style="color:#ff0000" data-title="未收"><%= remain %></div>
        <% else %>
          <div class="table_cell numeric" data-title="未收"><%= remain %></div>
        <% end %>
      </div>
      <div class='table_small'>
        <div class='table_cell'>备注</div>
        <div class="table_cell" style="text-align: left; padding-left: 15px" data-title="备注">
          <%= (!record.comment.nil? and !record.comment.blank?) ? record.comment : ' 无 ' %>
        </div>
      </div>

      <% if current_tenant.role == 'edit' or current_tenant.role == 'admin' then %>
        <div class='table_small'>
          <div class='table_cell'></div>
          <div class="table_cell"><%= link_to '编辑', edit_customer_record_path(record.customer_id, record) %></div>
        </div>
        <div class='table_small'>
          <div class='table_cell'></div>
          <div class="table_cell">
            <%= link_to '删除', customer_record_path(record.customer, record), method: :delete, data: { confirm: '确定删除吗？' } %>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
</div>
</div>

<br/><br/>
<div class="table">
  <% if current_tenant.role == 'edit' or current_tenant.role == 'admin' then %>
    <div class="row">
      <div class="col-xs-6">
        <%= link_to '编辑客户信息', edit_customer_path %>
      </div>
  <% end %>
  <% if current_tenant.role == 'admin' then %>

    <div class="col-xs-6">
      <%= link_to '删除客户', customer_path, method: :delete, data: { confirm: '确定删除客户吗？将清除所有的信息' } %>
    </div>
    </div>

  <% end %>
</div>