config/routes.rb
Rails.application.routes.draw do
  resources :employments

  root 'welcome#index'

  post 'welcome', to: 'welcome#set_current_year'

  get 'tenants/roles', to: 'welcome#roles'
  post 'tenants/roles', to: 'welcome#set_role'

  resources :customers do
    resources :records
  end

  resources :books do
    resources :fees do
      resources :fee_records

      get 'monthly_report', to: 'fees#show_monthly_report'

      get 'daily_trend', to: 'fees#show_daily_trend'
    end

    get 'monthly_report', to: 'books#show_monthly_report'
  end

  devise_for :tenants

end

app/models/book.rb
class Book < ActiveRecord::Base
  validates :book_name, presence: true, uniqueness: true
  has_many :fees, dependent: :destroy
  has_many :fee_records, through: :fees

  accepts_nested_attributes_for :fees
  accepts_nested_attributes_for :fee_records

  belongs_to :company



  def self.get_monthly_sum(book_id, year)

    records = Book.find(book_id).fee_records.where('year(fee_records.updated_at) =?', year)

    records.select(' month(fee_records.updated_at) as month,
                             sum(fee_records.debit) as debit, sum(fee_records.credit) as credit')
                         .group('month(fee_records.updated_at)')
                         .order('month(fee_records.updated_at) ASC')

    #Fee.group(:fee_name).where('year(updated_at) =?',"2016").includes(:fee_records).each
    # .sum {|a| a.fee_records}.map {|a| a.debit}
  end


end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]
  before_action :set_companies, only: [:new]

  # GET /fees
  # GET /fees.json
  def index
    @book = Book.all.where(company_id: session[:current_companies].collect(&:id))
    redirect_to root_path
  end

  def show

    if Book.find_by_id(params[:id])
      @book = Book.find_by_id(params[:id])
      @fees = @book.fees
      @debit_sum = @book.fee_records.where('left(fee_records.updated_at,4) =?', session[:current_year]).sum('debit').round(2)
      @credit_sum = @book.fee_records.where('left(fee_records.updated_at,4) =?', session[:current_year]).sum('credit').round(2)

      @group_by_fee = @fees.select('fees.book_id, fees.id, fees.fee_name,
                            sum(fee_records.debit) as debit, sum(fee_records.credit) as credit')
                           .joins("LEFT OUTER JOIN fee_records on fees.id=fee_records.fee_id
                                and left(fee_records.updated_at,4) = #{session[:current_year]}")
                           .group('fees.book_id, fees.id, fees.fee_name')
                           .order('fees.updated_at DESC')

    else
      redirect_to root_path
    end
  end

  # GET /fees/new
  def new
    @book = Book.new

  end

  # GET /fees/1/edit
  def edit
    @book = Book.find(params[:id])

  end

  # POST /fees
  # POST /fees.json
  def create
    @book = Book.new(book_params)
    #@book.tenant_id = current_tenant.id
    #binding.pry
    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: '创建成功.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fees/1
  # PATCH/PUT /fees/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: '更新成功.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy

    @book.destroy
    respond_to do |format|
      format.html { redirect_to root_url, notice: '账本删除成功.' }
      format.json { head :no_content }
    end
  end

  def show_monthly_report
    if Book.find_by_id(params[:book_id])
      @book = Book.find(params[:book_id])
      @records = @book.fee_records.where('year(fee_records.updated_at) =?', session[:current_year])
      @debit_sum = @records.sum("debit")
      @credit_sum = @records.sum("credit")
      @groupby_month = Book.get_monthly_sum(params[:book_id], session[:current_year])
    else
      redirect_to root_path
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_book
    if Book.find_by_id(params[:id])
      @book = Book.find(params[:id])
    else
      redirect_to root_path
    end
  end

  def set_companies
    @companies = Company.where(id: session[:current_companies])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def book_params
    params.require(:book).permit(:book_name, :company_id)
  end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<%= form_for(@book) do |f| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> 保存出错了:</h2>

      <ul>
        <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="divTable">
    <div class="divTableBody">
      <div class="divTableRow">
        <div class="divTableCell">
          <%= f.label '公司名称' %>
        </div>
        <div class="divTableCell">
          <%= f.select :company_id,
                       options_for_select(@companies.all.collect { |p| [p.name, p.id] }),
                       { :include_blank => true },
                       { style: 'font-size:18px' }
          %>
        </div>
      </div>
      <div class="divTableRow">
        <div class="divTableCell">
          <%= f.label '账本名称' %><br>
        </div>
        <div class="divTableCell">
          <%= f.text_field :book_name %>
        </div>
      </div>
      <div class="divTableRow">
        <div class="divTableCell">
          <%= f.submit '保存', class: 'btn btn-primary' %>
        </div>
        <div class="divTableCell">
          <%= link_to '返回', books_path(@book), class: 'btn btn-primary' %>
        </div>
      </div>
    </div>
  </div>




<% end %>

app/views/books/edit.html.erb
<h1>编辑费项信息</h1>
<%= link_to '返回费项', fee_path(@fee) %>
<br>
<br>
<%= render 'form' %>

app/views/books/new.html.erb
<h1>新收支账本</h1>
<%= link_to '返回', root_path, class:'btn btn-primary' %>
<br>

<%= render 'form' %>

app/views/books/show.html.erb
<% content_for :title, @book.book_name %>


<div class="fixed-box">
  <ol class="breadcrumb">
    <li><%= link_to '主页', root_path %></li>
    <li class="active"> <%= @book.book_name %></li>
  </ol>
</div>

<br>

<div class="row">
  <% if current_tenant.role == 'admin' or current_tenant.role == 'edit' then %>
    <div class="col-xs-3 col-md-1">
      <%= link_to '新建费项', new_book_fee_path(@book), class: 'btn btn-primary' %>
    </div>
  <% end %>

  <div class="col-xs-3 col-md-1">
    <%= link_to '月报', book_monthly_report_path(@book), class: 'btn btn-primary' %>
  </div>
</div>
<br>

<script type="text/javascript" charset="utf-8">
    $(function () {
        new Highcharts.Chart({
            chart: {
                plotBackgroundColor: null,
                plotBorderWidth: null,
                plotShadow: false,
                type: 'pie',
                renderTo: "orders_chart"
            },
            plotOptions: {
                pie: {
                    allowPointSelect: true,
                    cursor: 'pointer',
                    dataLabels: {
                        enabled: true,
                        format: '<b>{point.name}</b>: {point.percentage:.1f} %',
                        style: {
                            color: (Highcharts.theme && Highcharts.theme.contrastTextColor) || 'black'
                        }
                    }
                }
            },
            title: {
                text: "支出费项分布图"
            },

            tooltip: {
                valueSuffix: ' 元'
            },


            series: [{
                name: '支出',
                colorByPoint: true,
                data: <%=
                group_by_fee_no_nil = @group_by_fee.reject { |o| o.debit.nil? }
                raw group_by_fee_no_nil.map { |o| [o.fee_name, o.debit ] }.compact.to_s
                 %>

            }]
        });
    });
</script>
<div id="orders_chart"></div>


<div class="table sumTable">
  <div class="theader">
    <div class="table_header">总收入</div>
    <div class="table_header">总支出</div>
    <div class="table_header">总余额</div>
  </div>
  <div class="table_row">
    <div class='table_small'>
      <div class='table_cell'>总收入</div>
      <div class="table_cell head_sum" ><%= @credit_sum.to_f.round(2) %></div>
    </div>
    <div class='table_small'>
      <div class='table_cell'>总支出</div>
      <div class="table_cell head_sum" ><%= @debit_sum.to_f.round(2) %></div>
    </div>
    <div class='table_small'>
      <div class='table_cell'>总余额</div>
      <div class="table_cell head_sum" <% if @credit_sum - @debit_sum < 0%> style="color:red" <% end %> >
        <%= (@credit_sum - @debit_sum).to_f.round(2) %>
      </div>
    </div>
  </div>
</div>

<div class="table listTable">
  <div class="theader">
    <div class="table_header">费项</div>
    <div class="table_header">收入</div>
    <div class="table_header">支出</div>
  </div>
  <%
    @group_by_fee.each do |rec|
      de = rec.debit.to_f.round(2)
      cr = rec.credit.to_f.round(2)
      #cr = rec.fee_records.where('left(fee_records.updated_at,4) =?', session[:current_year]).sum('credit')
  %>
  <div class="table_row">
    <div class='table_small'>
      <div class='table_cell'>费项</div>
      <div class="table_cell"><%= link_to rec.fee_name, book_fee_path(rec.book_id, rec.id) %></div>
    </div>
    <div class='table_small'>
      <div class='table_cell'>收入</div>
      <div class="table_cell numeric"><%= cr %></div>
    </div>
    <div class='table_small'>
      <div class='table_cell'>支出</div>
      <div class="table_cell numeric"><%= de %></div>
    </div>
  </div>
  <% end %>

</div>


<% if current_tenant.role == 'admin' then %>
  <%= link_to '删除账本', book_path, method: :delete, data: { confirm: '确定删除吗？将清除该账本所有信息！！' } %>
<% end %>

app/views/books/show_monthly_report.html.erb
<% content_for :title, @book.book_name+'月报' %>

<div class="fixed-box">
  <ol class="breadcrumb">
    <li><%= link_to '主页', root_path %></li>
    <li><%= link_to @book.book_name, book_path(@book) %></li>
    <li class="active"> <%= @book.book_name+'月报' %></li>
  </ol>
</div>

<br><br>
<script type="text/javascript" charset="utf-8">
    $(function () {
        new Highcharts.Chart({
            chart: {
                type: 'bar',
                renderTo: "orders_chart"
            },
            plotOptions: {
                bar: {
                    dataLabels: {
                        enabled: true
                    }
                }
            },
            title: {
                text: "月收支对比报表"
            },
            xAxis: {
                categories: <%=  @groupby_month.map{|a| a.month} %>,
                title: {text: "月"}
            },
            yAxis: {
                title: {
                    text: "元"
                },
                labels: {
                    overflow: 'justify'
                }

            },
            tooltip: {
                valueSuffix: ' 元'
            },


            series: [
                {
                    name: '支出',
                    data: <%= @groupby_month.map{|a| a.debit} %>,
                    color: '#FF3333'
                },
                {
                    name: '收入',
                    color: '#009900',
                    data: <%= @groupby_month.map{|a| a.credit} %>
                }
            ]
        });
    });
</script>
<div id="orders_chart"></div>
<div id="no-more-tables">

  <table class="table table-responsive table-striped table-hover table-condensed table-bordered " style="border: 2px solid orange">
    <thead>
    <tr>
      <th>总收入</th>
      <th>总支出</th>
      <th>总余额</th>

    </tr>
    </thead>
    <tbody>
    <tr>
      <td class="head_sum" data-title="总收入"><%= @credit_sum %></td>
      <td class="head_sum" data-title="总支出"><%= @debit_sum %></td>
      <td class="head_sum" data-title="总余额"><%= @credit_sum - @debit_sum %></td>
    </tr>
    </tbody>
  </table>


  <table class="table table-responsive table-striped table-hover table-condensed table-bordered ">
    <thead>
    <tr>
      <th>月份</th>
      <th>收入</th>
      <th>支出</th>
    </tr>
    </thead>

    <tbody>
    <% @groupby_month.each do |record| %>
        <tr>
          <td class="numeric" data-title="月份">
            <%= record.month.to_s+"月" %>
          </td>
          <td class="numeric" data-title="收入"><%= record.credit.to_f.round(2) %></td>
          <td class="numeric" data-title="支出"><%= record.debit.to_f.round(2) %></td>

        </tr>
    <% end %>

    </tbody>
  </table>
</div>