config/routes.rb
Rails.application.routes.draw do
  resources :employments

  root 'welcome#index'

  post 'welcome', to: 'welcome#set_current_year'

  get 'tenants/roles', to: 'welcome#roles'
  post 'tenants/roles', to: 'welcome#set_role'

  resources :customers do
    resources :records
  end

  resources :books do
    resources :fees do
      resources :fee_records

      get 'monthly_report', to: 'fees#show_monthly_report'

      get 'daily_trend', to: 'fees#show_daily_trend'
    end

    get 'monthly_report', to: 'books#show_monthly_report'
  end

  devise_for :tenants

end

app/models/fee.rb
class Fee < ActiveRecord::Base
  validates :fee_name, presence: true, uniqueness: {scope: :book}

  belongs_to :book
  has_many :fee_records, dependent: :destroy
end

app/controllers/fees_controller.rb
class FeesController < ApplicationController
  before_action :set_fee, only: [:show, :edit, :update, :destroy]

  def show
    if Book.find_by_id(params[:book_id])
      @book = Book.find(params[:book_id])
      @fee = @book.fees.find(params[:id])
      @records = @fee.fee_records.where('left(fee_records.updated_at,4) =?', session[:current_year]).order('updated_at DESC')
      @debit_sum = @records.sum("debit")
      @credit_sum =@records.sum("credit")
    else
      redirect_to root_path
    end
  end


  def show_monthly_report
    if Book.find_by_id(params[:book_id])
      @book = Book.find(params[:book_id])
      @fee = @book.fees.find(params[:fee_id])
      @records = @fee.fee_records.where('year(fee_records.updated_at) =?', session[:current_year])
      @debit_sum = @records.sum("debit")
      @credit_sum =@records.sum("credit")

      @groupby_month = @records.select(' month(updated_at) as month,
                             sum(fee_records.debit) as debit, sum(fee_records.credit) as credit')
                           .group('month(updated_at)')
                           .order('month(updated_at) ASC')

      #  binding.pry

    else
      redirect_to root_path
    end
  end

  def show_daily_trend
    if Book.find_by_id(params[:book_id])
      @book = Book.find(params[:book_id])
      @fee = @book.fees.find(params[:fee_id])
      @records = @fee.fee_records.where('year(fee_records.updated_at) =?', session[:current_year])
      @debit_sum = @records.sum("debit")
      @credit_sum =@records.sum("credit")

      @groupby_date = @records.select(' date(updated_at) as date,
                             sum(fee_records.credit-fee_records.debit) as income')
                           .group('date(updated_at)')
                           .order('date(updated_at) ASC')

      balance = 0

      @daily_balance = @groupby_date.map do |a|
        {
            :date => a.date.to_formatted_s(:number),
            :balance => balance = balance + a.income
        }
      end

    else
      redirect_to root_path
    end
  end
  # GET /fees/new
  def new
    @book = Book.find(params[:book_id])
    @fee = Fee.new
  end

  # GET /fees/1/edit
  def edit
    @book = Book.find(params[:book_id])
    @fee = @book.fees.find(params[:id])

  end

  def create
    @book = Book.find(params[:book_id])
    @fee =  @book.fees.create(fee_params)

    if @fee.save
      redirect_to book_path(@book)

    else
      render :new

    end
  end

  # PATCH/PUT /fees/1
  # PATCH/PUT /fees/1.json
  def update
    respond_to do |format|
      if @fee.update(fee_params)
        format.html { redirect_to book_fee_path(@book,@fee), notice: '费项更新成功.' }
        format.json { render :show, status: :ok, location: @fee }
      else
        format.html { render :edit }
        format.json { render json: @fee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fees/1
  # DELETE /fees/1.json
  def destroy
    book_id = @fee.book_id
    @fee.destroy
    redirect_to  book_path(book_id)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fee
      @book = Book.find(params[:book_id])
      @fee = @book.fees.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def fee_params
      params.require(:fee).permit(:fee_name)
    end
end

app/helpers/fees_helper.rb
module FeesHelper
end

app/views/fees/_form.html.erb
<%= form_for([@book, @fee]) do |f| %>
    <% if @fee.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@fee.errors.count, "error") %> 保存出错了:</h2>

          <ul>
            <% @fee.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

  <div class="field">
    <%= f.label '费项名称' %><br>
    <%= f.text_field :fee_name %>
  </div>
  <div class="actions">
    <%= f.submit '保存', class:'btn btn-primary' %>
  </div>
<% end %>

app/views/fees/edit.html.erb
<h1>编辑费项信息</h1>
<%= link_to '返回费项', book_fee_path(@book,@fee) , class:'btn btn-primary' %>
<%= render 'form' %>

app/views/fees/new.html.erb
<h1>新建费项</h1>
<div class="actions">
  <%= link_to '返回', book_path(@book), class: 'btn btn-primary' %>
</div>
<%= render 'form' %>

app/views/fees/show.html.erb
<% content_for :title, @fee.fee_name + '明细' %>
<script>

    $(document).ready(function () {
        //日期选择器
        $('#sandbox-container input').datepicker({
            format: "yyyy/mm/dd",
            language: "zh-CN",
            todayHighlight: true
        });

        //根据price字段计算支出金额
        $(':input[name*="price"]').change(function () {
            var price = $(this).val();
            // Obtain the selling price from server
            var quantity = $(':input[name*="quantity"]').val()
            $(':input[name*="debit"]').val(quantity * price);
        });

        //根据quantity字段计算支出金额
        $(':input[name*="quantity"]').change(function () {
            var quantity = $(this).val();
            // Obtain the selling price from server
            var price = $(':input[name*="price"]').val()
            $(':input[name*="debit"]').val(quantity * price);
        });
    });
</script>


<div class="fixed-box">
  <ol class="breadcrumb">
    <li><%= link_to '主页', root_path %></li>
    <li><%= link_to @book.book_name, book_path(@book) %></li>
    <li class="active"> <%= @fee.fee_name + '明细' %></li>
  </ol>
</div>

<br>




<!--
<p>
  <strong>账本名称:</strong>
  <%= @book.book_name %>
</p>
-->

<%= link_to '月报', book_fee_monthly_report_path(@book, @fee), class: 'btn btn-primary' %>
<%= link_to '日趋势', book_fee_daily_trend_path(@book, @fee), class: 'btn btn-primary' %>


<div class="divTable">

  <% if current_tenant.role == 'edit' or current_tenant.role == 'admin' then %>
    <%= form_for([@book, @fee, @fee.fee_records.build]) do |f| %>

      <div class="numeric" data-title="日期">

        <!--%= Time.now.strftime('%Y/%m/%d') %-->
        <div id="sandbox-container">
          <label for="date_input">日期:</label>
          <%= f.text_field :updated_at, 'data-provide' => 'datepicker',
                           value: (Time.now.strftime('%Y') > session[:current_year]) ? session[:current_year] + '/12/31' : Time.now.strftime('%Y/%m/%d'),
                           style: ' width:90%;',
                           id: 'date_input' %>
        </div>

      </div>
      <div class="numeric" data-title="收入">
        <label for="credit_input">收入:</label>
        <%= f.number_field :credit, value: 0, min: 0, max: 999999, inputmode: "numeric", :step => '0.01',
                           class: 'amount_input',
                           id: 'credit_input',
                           style: ' width:90%;',
                           pattern: "[0-9]*",
                           onfocus: "if(this.value == '0') { this.value = ''; }",
                           onblur: "if(this.value == '') { this.value = 0 ; }" %>
      </div>
      <div class="numeric" data-title="支出-数量">
        <label for="quantity_input">支出-数量:</label>
        <%= f.number_field :quantity, value: 1, min: 0, max: 999999, inputmode: "numeric", :step => '0.01',
                           class: 'amount_input',
                           pattern: "[0-9]*",
                           id: 'quantity_input',
                           style: ' width:90%;',
                           onfocus: "if(this.value == '1') { this.value = ''; }",
                           onblur: "if(this.value == '') { this.value = 1 ; }" %>
      </div>
      <div class="numeric" data-title="支出-单价">
        <label for="price_input">支出-单价:</label>
        <%= f.number_field :price, value: 0, min: 0, max: 999999, inputmode: "numeric", :step => '0.01',
                           class: 'amount_input',
                           id: 'price_input',
                           style: ' width:90%;',
                           pattern: "[0-9]*",
                           onfocus: "if(this.value == '0') { this.value = ''; }",
                           onblur: "if(this.value == '') { this.value = 0 ; }" %>
      </div>
      <div class="numeric" data-title="支出-金额">
        <label for="amount_input">支出-金额:</label>
        <%= f.number_field :debit, value: 0, min: 0, max: 999999, inputmode: "numeric", :step => '0.01',
                           class: 'amount_input',
                           id: 'amount_input',
                           style: ' width:90%;',
                           pattern: "[0-9]*",
                           onfocus: "if(this.value == '0') { this.value = ''; }",
                           onblur: "if(this.value == '') { this.value = 0 ; }",
                           readonly: true
        %>
      </div>
      <div class="numeric" data-title="备注">
        <label for="comment_input">备注:</label>
        <%= f.text_field :comment, id: 'comment_input', style: 'width:90%' %>
      </div>
      <div colspan="2"> <%= f.submit '保存新记录', class: 'btn btn-primary btn-sm btn-block btn-submit' %></div>
    <% end %>
  <% end %>
</div>
<br>
<br>




<div class="table sumTable">
  <div class="theader">
    <div class="table_header">费项</div>
    <div class="table_header">收入</div>
    <div class="table_header">支出</div>
    <div class="table_header">余额</div>
  </div>
  <div class="table_row">
    <div class='table_small'>
      <div class='table_cell'>费项</div>
      <div class="table_cell"><%= @fee.fee_name %></div>
    </div>
    <div class='table_small'>
      <div class='table_cell'>收入</div>
      <div class="table_cell numeric"><%= @credit_sum.round(2) %></div>
    </div>
    <div class='table_small'>
      <div class='table_cell'>支出</div>
      <div class="table_cell numeric"><%= @debit_sum.to_f.round(2) %></div>
    </div>
    <div class='table_small'>
      <div class='table_cell'>余额</div>
      <div class="table_cell numeric"
           <% if @credit_sum - @debit_sum < 0 %> style="color:red"
           <% end %> >
        <%= (@credit_sum - @debit_sum).to_f.round(2) %>
      </div>
    </div>
  </div>
</div>

<br/>
<div class="table listTable">
  <div class="theader">
    <div class="table_header">日期</div>
    <div class="table_header">收入</div>
    <div class="table_header">支出-数量</div>
    <div class="table_header">支出-单价</div>
    <div class="table_header">支出-金额</div>
    <div class="table_header">备注</div>
    <% if current_tenant.role == 'admin' or current_tenant.role == 'edit' then %>
        <div class="table_header"></div>
        <div class="table_header"></div>
    <% end %>
  </div>
  <% @records.each do |record| %>
    <div class="table_row">
      <div class='table_small'>
        <div class='table_cell'>日期</div>
        <div class="table_cell"><%= record.updated_at.strftime('%Y/%m/%d') %></div>
      </div>
      <div class='table_small'>
        <div class='table_cell'>收入</div>
        <div class="table_cell numeric"><%= record.credit %></div>
      </div>
      <div class='table_small'>
        <div class='table_cell'>支出-数量</div>
        <div class="table_cell numeric"><%= record.quantity %></div>
      </div>
      <div class='table_small'>
        <div class='table_cell'>支出-单价</div>
        <div class="table_cell numeric"><%= record.price %></div>
      </div>
      <div class='table_small'>
        <div class='table_cell'>支出-金额</div>
        <div class="table_cell numeric"><%= record.debit %></div>
      </div>
      <div class='table_small'>
        <div class='table_cell'>备注</div>
        <div class="table_cell numeric" style="text-align: left; padding-left: 15px">
          <%= (!record.comment.nil? and !record.comment.blank?) ? record.comment : '无' %>
        </div>
      </div>
      <% if current_tenant.role == 'admin' or current_tenant.role == 'edit' then %>
        <div class='table_small'>
          <div class='table_cell'></div>
          <div class="table_cell ">
            <%= link_to '编辑', edit_book_fee_fee_record_path(@book.id, record.fee_id, record) %>
          </div>
        </div>
        <div class='table_small'>
          <div class='table_cell'></div>
          <div class="table_cell ">
            <%= link_to '删除', book_fee_fee_record_path(@book.id, record.fee_id, record), method: :delete, data: { confirm: '确定删除吗？' } %>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>

</div>
<br><br>


<div class="row">
  <% if current_tenant.role == 'admin' or current_tenant.role == 'edit' then %>
    <div class="col-xs-6">
      <%= link_to '编辑费项名称', edit_book_fee_path(@book, @fee) %>
    </div>
  <% end %>
  <% if current_tenant.role == 'admin' then %>
    <div class="col-xs-4">
      <%= link_to '删除费项', book_fee_path, method: :delete, data: { confirm: '确定删除费项吗？将清除该费项所有信息！！' } %>
    </div>
  <% end %>
</div>

app/views/fees/show_daily_trend.erb
<% content_for :title, @fee.fee_name+'日趋势' %>

<div class="fixed-box">
  <ol class="breadcrumb">
    <li><%= link_to '主页', root_path %></li>
    <li><%= link_to @fee.fee_name, book_fee_path(@book, @fee) %></li>
    <li class="active"> <%= @fee.fee_name+'日趋势' %></li>
  </ol>
</div>

<br>
<br>


<script type="text/javascript" charset="utf-8">
    $(function () {

        daily_ba = <%= raw @daily_balance.to_json %>;
        var date_json = new Array();
        var balance_json = new Array();
        for (i = 0; i < daily_ba.length; i++) {
            date_json.push(daily_ba[i].date);
            balance_json.push(daily_ba[i].balance);
        }


        new Highcharts.Chart({
            chart: {
                type: 'line',
                renderTo: "orders_chart"
            },
            plotOptions: {
                bar: {
                    dataLabels: {
                        enabled: true
                    }
                }
            },
            title: {
                text: "日趋势"
            },
            xAxis: {
                categories: date_json
            },
            yAxis: {
                title: {
                    text: "元"
                },
                labels: {
                    overflow: 'justify'
                }

            },
            tooltip: {
                valueSuffix: ' 元'
            },


            series: [
                {
                    name: '余额',
                    data: balance_json,
                    color: '#FF3333'
                }
            ]
        });
    });



</script>

<div id="orders_chart"></div>


<div id="no-more-tables">
  <table class="table table-responsive table-striped table-hover table-condensed table-bordered " style="border: 2px solid orange">
    <thead>
    <tr>
      <th>费项</th>
      <th>余额</th>
    </tr>
    </thead>
    <tbody>
    <tr>
      <td class="head_sum" data-title="费项"><%= @fee.fee_name %></td>

      <td class="head_sum" data-title="余额"><%= (@credit_sum-@debit_sum).round(2) %></td>
    </tr>

    </tbody>
  </table>

  <table class="table table-responsive table-striped table-hover table-condensed table-bordered ">
    <thead>
    <tr>
      <th>月份</th>
      <th>余额</th>
    </tr>
    </thead>

    <tbody>
    <% @groupby_date.each do |record| %>

    <tr>
          <td class="numeric" data-title="月份">
            <%= record.date.to_s %>
          </td>
          <td class="numeric" data-title="收入"><%= record.income.to_f.round(2) %></td>

        </tr>
    <% end %>

    </tbody>
  </table>

</div>

app/views/fees/show_monthly_report.html.erb
<% content_for :title, @fee.fee_name+'月报' %>

<div class="fixed-box">
  <ol class="breadcrumb">
    <li><%= link_to '主页', root_path %></li>
    <li><%= link_to @fee.fee_name, book_fee_path(@book, @fee) %></li>
    <li class="active"> <%= @fee.fee_name+'月报' %></li>
  </ol>
</div>

<br>
<br>


<script type="text/javascript" charset="utf-8">
    $(function () {
        new Highcharts.Chart({
            chart: {
                type: 'bar',
                renderTo: "orders_chart"
            },
            plotOptions: {
                bar: {
                    dataLabels: {
                        enabled: true
                    }
                }
            },
            title: {
                text: "月收支对比报表"
            },
            xAxis: {
                categories: <%=  @groupby_month.map{|a| a.month} %>,
                title: {text: "月"}
            },
            yAxis: {
                title: {
                    text: "元"
                },
                labels: {
                    overflow: 'justify'
                }

            },
            tooltip: {
                valueSuffix: ' 元'
            },


            series: [
                {
                    name: '支出',
                    data: <%= @groupby_month.map{|a| a.debit} %>,
                    color: '#FF3333'
                },
                {
                    name: '收入',
                    color: '#009900',
                    data: <%= @groupby_month.map{|a| a.credit} %>
                }
            ]
        });
    });
</script>
<div id="orders_chart"></div>


<div id="no-more-tables">
  <table class="table table-responsive table-striped table-hover table-condensed table-bordered " style="border: 2px solid orange">
    <thead>
    <tr>
      <th>费项</th>
      <th>收入</th>
      <th>支出</th>
      <th>余额</th>
    </tr>
    </thead>
    <tbody>
    <tr>
      <td class="head_sum" data-title="费项"><%= @fee.fee_name %></td>
      <td class="head_sum" data-title="收入"><%= @credit_sum.round(2) %></td>
      <td class="head_sum" data-title="支出"><%= @debit_sum.round(2) %></td>
      <td class="head_sum" data-title="余额"><%= (@credit_sum-@debit_sum).round(2) %></td>
    </tr>

    </tbody>
  </table>

  <table class="table table-responsive table-striped table-hover table-condensed table-bordered ">
    <thead>
    <tr>
      <th>月份</th>
      <th>收入</th>
      <th>支出</th>
    </tr>
    </thead>

    <tbody>
    <% @groupby_month.each do |record| %>

    <tr>
          <td class="numeric" data-title="月份">
            <%= record.month.to_s+"月" %>
          </td>
          <td class="numeric" data-title="收入"><%= record.credit.to_f.round(2) %></td>
          <td class="numeric" data-title="支出"><%= record.debit.to_f.round(2) %></td>

        </tr>
    <% end %>

    </tbody>
  </table>

</div>

app/views/fees/temp.erb
//  data: <%= groupby_date = @groupby_date.reject { |o| o.income.nil? }
              raw groupby_date.map { |o| [o.date.to_formatted_s(:number) , o.income ] }.compact.to_s %>,